# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "96e8a9edf06fbe28957bc93a4f00ddc9"
application_url = "https://voicero-app-is117a-nj.vercel.app/"
embedded = true
name = "voicero-app-is117a-nj"
handle = "voicero-app-is117a-nj"

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-01"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

  [[webhooks.subscriptions]]
  compliance_topics = [ "customers/data_request", "customers/redact", "shop/redact" ]
  uri = "/webhooks/gdpr"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_content,read_products,read_discounts,write_content,read_metaobjects,write_metaobjects,read_inventory,read_product_listings,customer_read_customers,customer_write_customers,customer_read_orders,customer_write_orders,read_legal_policies,unauthenticated_read_customers,unauthenticated_write_customers,unauthenticated_read_content,unauthenticated_read_metaobjects,read_orders,read_customers,write_customers,read_returns,write_returns,write_orders"

[auth]
redirect_urls = [
  "https://voicero-app-is117a-nj.vercel.app/auth/callback",
  "https://voicero-app-is117a-nj.vercel.app/auth/shopify/callback",
  "https://voicero-app-is117a-nj.vercel.app/api/auth/callback"
]

[pos]
embedded = false

[app_proxy]
url = "https://voicero-app-is117a-nj.vercel.app/app/proxy"
subpath = "proxy"
prefix = "apps"
